name: Push to GCR GitHub Action

on:
  push:
    branches:
      - main

jobs:
  deploy-api:
    name: Deploy BURNDEX API Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Push Container to GCR
        uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: us.gcr.io
          project_id: burndex
          image_name: bx-api
      
      - name: Deploy Container to App Engine
        run: |
          gcloud app deploy --image-url=us.gcr.io/burndex/bx-api